### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by ShariJoosten** [CrowdStrike/gofalcon#122]
Hello,

Around a month ago a new feature in our application caused around ~1000 bugs every week. Investigation showed that there was an bug in the API of Crowdstrike. This bug has now finally been resolved, and the updated swagger works: The bug is no longer there. Sadly enough we're still dealing with this bug in our application because this API Client Library is sending the request in an incorrect way. I've cloned this repository, and on main it already works perfectly because the codebase has already been re-generated based on the most recent swagger. So the only thing missing for us is a new release containing the updated code base on the most recent swagger documentation :D

Thanks in advance,

Shari

**Comment by isimluk** [comment]
Hello @ShariJoosten,

I am sorry for the trouble you have experienced. I have released version v0.2.10 out of the master. https://github.com/CrowdStrike/gofalcon/releases/tag/v0.2.10
