### ISSUE TITLE
module path typo

### ISSUE THREAD

**Issue by jlagermann** [CrowdStrike/gofalcon#132]
When trying to use this Go library, I get the following error.

```
$ go get github.com/CrowdStrike/gofalcon/falcon
go: downloading github.com/CrowdStrike/gofalcon v0.2.11
go get: github.com/CrowdStrike/gofalcon@v0.2.11: parsing go.mod:
        module declares its path as: github.com/crowdstrike/gofalcon
                but was required as: github.com/CrowdStrike/gofalcon
```

**Comment by redhatrises** [comment]
You are getting this error because of running:

```
$ go get github.com/CrowdStrike/gofalcon/falcon
```

There is no `falcon` go module.

Both the following commands should work for you:

```
$ go get github.com/CrowdStrike/gofalcon
```

or

```
$ go get github.com/crowdstrike/gofalcon
```

**Comment by isimluk** [comment]
@jlagermann Thanks for getting in touch. You are right, the CamelCase in the installation instructions has to be avoided. Correct refer to gofalcon is to use lowercase path.

I have fixed the installation instructions!
