### ISSUE TITLE
Unable to download all sensors

### ISSUE THREAD

**Issue by mikemadden42** [CrowdStrike/gofalcon#190]
Hello, I am running into issues with the falcon_sensor_download [example](https://github.com/CrowdStrike/gofalcon/tree/main/examples/falcon_sensor_download):

```bash

$ sw_vers
ProductName:	macOS
ProductVersion:	12.2
BuildVersion:	21D49

$ go version
go version go1.17.6 darwin/amd64

$ ./falcon_sensor_download --all
panic: Suspicious file location: Identity Protection DC Sensor/identity_protection_dc_sensor_6.35.19705.BetaBarb.msi

goroutine 1 [running]:
main.download(0xc00021e600, 0xc0004e0000, {0xc00010e0c0, 0x53})
	/Users/hulk/src/gofalcon/examples/falcon_sensor_download/main.go:98 +0x2f9
main.downloadAllSensors(0xc00029fef8)
	/Users/hulk/src/gofalcon/examples/falcon_sensor_download/main.go:217 +0xb0
main.main()
	/Users/hulk/src/gofalcon/examples/falcon_sensor_download/main.go:53 +0x8fb
```

It looks like the path to sensor downloads has the `/` in them, and this line is causing the panic:
https://github.com/CrowdStrike/gofalcon/blob/main/examples/falcon_sensor_download/main.go#L97

What do you think about removing the check for a `/`?

**Comment by isimluk** [comment]
Thank You for the report.

Let me know if you require new [release build](https://github.com/CrowdStrike/gofalcon/releases) with the fix.

**Comment by mikemadden42** [comment]
@isimluk I'm happy to make a PR.  Do you think removing the `strings.Contains(safeLocation, "/")` is sufficient?

**Comment by isimluk** [comment]
Oh. I am sorry, I already made a PR early in the morning: https://github.com/CrowdStrike/gofalcon/pull/191

**Comment by mikemadden42** [comment]
No problem.... https://github.com/CrowdStrike/gofalcon/pull/191 looks great. 👍🏼

**Comment by mikemadden42** [comment]
> Let me know if you require new [release build](https://github.com/CrowdStrike/gofalcon/releases) with the fix.

This may not warrant a release.  I'm fine with rebuilding from `master` once your PR is merged.
