### ISSUE TITLE
Discover | limit must be less than or equal to 10000

### ISSUE THREAD

**Issue by zeknox** [CrowdStrike/gofalcon#196]
The example script for [discover](https://github.com/CrowdStrike/gofalcon/blob/main/examples/falcon_discover_host_details/main.go) runs into a panic condition when it hits a limit defined within the API endpoint.

Below is sample error
```
panic: [GET /discover/queries/hosts/v1][400] queryHostsBadRequest  &{Errors:[{Code:400 Message:offset 10000 and limit 100 are invalid; offset + limit must be less than or equal to 10000}] Meta:PoweredBy:discover-api QueryTime:0.007191935 TraceID:b8df171b-9f9f-4b0c-90cd-c8b36280328e}}
[BODY {"errors":[{"code":400,"message":"offset 10000 and limit 100 are invalid; offset + limit must be less than or equal to 10000"}],"meta":{"powered_by":"discover-api","query_time":0.007191935,"trace_id":"b8df171b-9f9f-4b0c-90cd-c8b36280328e"}}]
```

**Comment by zeknox** [comment]
most definitely

**Comment by isimluk** [comment]
Thanks. It turns out that pagination on this particular end-point is not yet ready to be fixed on the client side, but require server side fix. I have notified the appropriate team.

**Comment by zeknox** [comment]
Thanks for the update.  For the short-term; ended up leveraging the `client.Hosts.QueryDevicesByFilter()` method which works

**Comment by isimluk** [comment]
I am closing this issue as we have established this is not issue to on the client side (gofalcon). Please open a support ticket to get timely updates on the fixes of the server side.
