### ISSUE TITLE
Hosts: provide way to fetch all hosts and their details

### ISSUE THREAD

**Issue by hazcod** [CrowdStrike/gofalcon#204]
Hi, i'd like to retrieve all hosts and their tags. I tried `client.Hosts.QueryDevicesByFilter` but this only returns the host IDs.
Querying every host separately is very expensive. Is there a method I missed?

**Comment by isimluk** [comment]
Hello @hazcod,

This is really good question. You definitely don't need to run 1+N query. You just need to run 1+1 query. First, you ask for IDs of the hosts and second you ask for details. Both calls can be done in batches. I.e. first get 500 IDs, second get 500 details.

There is an example ([falcon_host_details](https://github.com/CrowdStrike/gofalcon/tree/main/examples/falcon_host_details)) that does exactly this and uses golang channels to be memory optimized on bigger environments.

Here are the relevant pieces of code:
 - [get host IDs in batches](https://github.com/CrowdStrike/gofalcon/blob/4effa96e4532892df75953b520e99b9a1ffe3e3c/examples/falcon_host_details/main.go#L93)
 - [get host details in batches](https://github.com/CrowdStrike/gofalcon/blob/4effa96e4532892df75953b520e99b9a1ffe3e3c/examples/falcon_host_details/main.go#L73)
 - [work through the batches](https://github.com/CrowdStrike/gofalcon/blob/4effa96e4532892df75953b520e99b9a1ffe3e3c/examples/falcon_host_details/main.go#L50-L55)

**Comment by hazcod** [comment]
Thanks for getting back, I just found it too:

```
	hostResult, err := client.Hosts.QueryDevicesByFilter(
		&hosts.QueryDevicesByFilterParams{
			Filter:  nil,
			Limit:   &falconAPIMaxRecords,
			Offset:  nil,
			Sort:    nil,
			Context: ctx,
		},
	)
...

	hostDetail, err := client.Hosts.GetDeviceDetails(&hosts.GetDeviceDetailsParams{
		Ids:        hostResult.Payload.Resources,
		Context:    ctx,
		HTTPClient: nil,
	})
...
```
