### ISSUE TITLE
gofalcon does not use HTTPS_PROXY settings

### ISSUE THREAD

**Issue by jlagermann** [CrowdStrike/gofalcon#260]
How do you configure gofalcon to use a proxy or honor the proxy environment variables?

**Comment by isimluk** [comment]
Hello @jlagermann,

I have run couple some test with the latest gofalcon and it seems to route the requests through the proxy. What leads you to believe that this does not work? What have you seen as an output?

What I did:
```
go build ./examples/simple && HTTPS_PROXY=http://localhost:8080/ ./simple
```

**Comment by isimluk** [comment]
Perfect! Thanks for the confirmation.
