### ISSUE TITLE
Custom User-Agent support?

### ISSUE THREAD

**Issue by dkindlund** [CrowdStrike/gofalcon#285]
Currently, there doesn't appear to be a way to provide the gofalcon client a custom User-Agent header.  Could this feature be added so that it would make it easier for partners to self-identify which applications are calling CrowdStrike APIs?

**Comment by mrxinu** [comment]
Hey @dkindlund! Steve here from Partner Engineering @ CrowdStrike. I haven't worked with `gofalcon` yet but let me have a look and I can maybe get a PR going to expose that for you.

**Comment by isimluk** [comment]
@mrxinu, I hope you don't mind, I have implemented this request in #293.

I have been on the long meeting, and this request has been a good filler for me to look at. 🤷

**Comment by mrxinu** [comment]
@isimluk Hehe, you know I don't mind. 👯‍♀️ 🙇‍♀️
