### ISSUE TITLE
IncidentType in streaming event is string but receiving ints

### ISSUE THREAD

**Issue by max-frank** [CrowdStrike/gofalcon#286]
We recently encountered the following JSON unmarshal error while streaming EDR events using gofalcon.

```
json: cannot unmarshal number into Go struct field Event.event.IncidentType of type string"
````
Going by what we can get from the Falcon web api/interface the incident type we received was `1`, but the (EventItem struct)[https://github.com/CrowdStrike/gofalcon/blob/302c29018eb1bfa0ea2dca53d746ae54c66f84af/falcon/models/streaming_models/models.go#L72] defines the field as `*string`. Also the the [domain incident struct](https://github.com/CrowdStrike/gofalcon/blob/302c29018eb1bfa0ea2dca53d746ae54c66f84af/falcon/models/domain_incident.go#L65) defines it as `int64`. So i suspect the streaming EvenItem struct should *be modified so that IncidentType is either:

- `int64`
- or `*IntOrString`

depending on if a string incident type is actually possible.

**Comment by isimluk** [comment]
Thank You for reporting this @max-frank.
