### ISSUE TITLE
Support for suppression rule management via API?

### ISSUE THREAD

**Issue by qa-ship-it** [CrowdStrike/gofalcon#323]
Hi there,

is there any plan on supporting management of suppression rules via API?
I think not being able to create or update suppression rules is really lacking the otherwise really good crowstrike API.

Best regards,
Marko

**Comment by jshcodes** [comment]
Hi @qa-ship-it -

Could you provide us more detail regarding which suppression rules you are referring to?  The APIs do support rule management for several of the service collections.

**Comment by qa-ship-it** [comment]
Sorry for the delayed answer!
What I'm looking for is the ability for CRUD operations on vulnerability suppression rules via API like they're managable using the falcon web interface.
So far, if I wanted to create a suppression rule for a certain vulnerability, I would need to open the web interface and fill in my data and filters into the form and submit it to create a suppression rule. 
Being able to achieve the same via the API would be a real game changer.

**Comment by ffalor** [comment]
Hey @qa-ship-it 

Thanks for the additional information. Are you referring to spotlight vulnerability suppression rules?

**Comment by ffalor** [comment]
At this time, I was not able to find any published endpoints in our api spec that could achieve this. I'd suggest reaching out to your contact within CrowdStrike and letting them know your need. They can route the feedback to the appropriate people.

If/when these endpoints are added to the api spec we will update the sdk to support them.

**Comment by ffalor** [comment]
closing this as part of a cleanup

If/when these endpoints are added to the api spec we will update the sdk to support them.
