### ISSUE TITLE
Panic may occur when calling Close method in StreamingHandle

### ISSUE THREAD

**Issue by rquinlivan** [CrowdStrike/gofalcon#346]
A panic can occur on this line if the StreamingHandle `Close()` method is called: https://github.com/CrowdStrike/gofalcon/blob/main/falcon/api_streaming.go#L122

The `Errors` channel is closed here: https://github.com/CrowdStrike/gofalcon/blob/main/falcon/api_streaming.go#L138

There is a race condition between the `Errors` channel close on line 138 and the write to the `Errors` channel on line 122. The block in 122 needs to ensure that the `Errors` channel is writeable before writing to it.

Impact:
- The client causes a panic

**Comment by ffalor** [comment]
Hey @rquinlivan ty for reporting this. This bug has been fixed in release v0.4.2
