### ISSUE TITLE
RTRDeleteQueuedSession returns error stating response status code does not match any response statuses defined for this endpoint in the swagger spec (status 200): {}

### ISSUE THREAD

**Issue by terrancedjones** [CrowdStrike/gofalcon#347]
When using the RTRDeleteQueueSession I'm sending the cloudID and i'm getting an error stating the following the Received response status code does not match any response statuses defined for this endpoint in the swagger spec (status 200): {}.

I sometimes get an error stating that it can't find the queued session although the RTRListQueuedSessions provides me with the necessary information.

**Comment by ffalor** [comment]
Hey this has been in fixed in `0.7.0-rc1` and future versions

**Comment by terrancedjones** [comment]
Ok great thanks
