### ISSUE TITLE
Using HostOverride alongside a client id & client secret

### ISSUE THREAD

**Issue by bionic-ido** [CrowdStrike/gofalcon#364]
Hey.
I've used the host-override in the API definition, in order to support host proxies.
I've wanted to ask regarding it, as I see that the initial auto-discover is always in front of the same hardcoded url, rather then the host override.
I've wanted to ask if there is a way to force it to use the host override for the auto-detect process as well, so it will be possible to support a proxy from a machine with strict firewall rules.

Thanks in advance!
Ido

**Comment by ffalor** [comment]
@bionic-ido `HostOverride` is the falcon cloud you want to hit. Can you explain how you've used it for proxies?

**Comment by bionic-ido** [comment]
Essentially I have yet to actually use it "for proxies".
I just initially thought that I would have been able to use it like that. The idea was that if a certain machine can only access the internet through a certain proxy, and it defined a path through "https://xxx.com" to "https://api.us-2.crowdstrike.com", then I would be able to define it in the HostOverride so that the entire autherization process & querying will be done in front of it (and the proxy would proxy it to the correct location).

Is there something to allow me to do such a thing, or is it currently only possible to have the auto-discover be made directly in front of the default api & the HostOverride only working in the rest of the code? I just wasn't sure if I wanted to "call it a bug" do to the fact autodiscover ignores HostOverride, or if it is intended behavior and there is another way to do what I want, or if it isn't possible due to a valid reason I'm not aware of.

Thanks in advance!
Ido

**Comment by ffalor** [comment]
Thanks for more information.

So this is more of a url redirect, in that situation `HostOverride` may work. The current behavior of doing autodiscover when `HostOverride` is provided seems wrong. If a `HostOverride` is provided then the autodiscover process should be skipped & `Cloud` ignored. I'll look more into it to make sure this is the case and if so raise a PR to change it.

On another note, If you want to use a proxy then you can use an environment variable like `HTTPS_PROXY`.

**Comment by ffalor** [comment]
@bionic-ido I've made the changes in my [hostoverride branch](https://github.com/ffalor/gofalcon/tree/hostoverride). Would you mind testing and see if this works the way you intend?

Thanks!

**Comment by bionic-ido** [comment]
Hey @ffalor. I've tested the fork (had to fork it myself due to go.mod module name not being updated but no worries).
It works like a charm, will be happy if it can be merged to the official sdk (currently using a fork in our code but would like to use the official sdk version of course :))

**Comment by bionic-ido** [comment]
I would like to add, btw, that it seems like this dodges a different bug.
While using the original code that used auto-discover, after a while, we started failing on the autodiscover step.
Looking into it, I found out that the oauth2 api started returning a rate limit exceeded error (even when we waited for hours in between), but only in front of the default api url it used for the auto-discover and not for our specific api region we put in the host-override.

You might want to look into it, as something is really weird on that front, though using the host-override currently seems to dodge the issue:
<img width="750" alt="image" src="https://github.com/CrowdStrike/gofalcon/assets/77567333/db1a4522-eab5-40ea-81d7-1347a12ed9a7">
<img width="704" alt="image" src="https://github.com/CrowdStrike/gofalcon/assets/77567333/46dc2752-a021-4b49-9d58-dcaea32dd0d6">

<img width="786" alt="image" src="https://github.com/CrowdStrike/gofalcon/assets/77567333/8fbee1bc-75f0-4c6b-905c-e155c428f6eb">
<img width="470" alt="image" src="https://github.com/CrowdStrike/gofalcon/assets/77567333/6ca45212-b03c-4700-9bf7-ecae3abf93c0">

(Not showing the secret & actual token intentionally lol)

**Comment by ffalor** [comment]
@bionic-ido I'll get this merged today. I'll look into this rate limit. Here are a few things

- the ouath2 endpoint has a smaller rate limit than normal endpoints. I believe ~300 based on IP. So make sure your code isn't creating new clients for every api call.
- I've seen a few ppl report similar issues hitting the api.crowdstrike.com url which may be the reason baseoverride worked since you skipped hitting this url (assuming you are saying the fork is what you were using). This looks to be a temporary issue on our end.

**Comment by bionic-ido** [comment]
We create a single API for all requests (on each separate run though, but they are mostly a hour apart so this wasn't the issue). But I'm unsure in any case.
Note that in crowdstrike documentation it was written that it has a 10 per minute limit or something if I'm not mistaken (for oauth2), so I expected much less really haha.
It definitely isn't based on IP though, as it happened across all our K8s machines and local machines simultanously, and stopped happening after we manually deleted all our API tokens & created a new one (just creating a new one didn't work until we deleted the older ones we previously used).

Hope this will help you debug. In any case, not using the auto-discover seems to have solved it for us, at least for now :)

Thanks!

**Comment by ffalor** [comment]
Hey @bionic-ido, release [v0.4.1](https://github.com/CrowdStrike/gofalcon/releases/tag/v0.4.1) has the changes to hostoverride. 

The 429 errors you were seeing seems to be widespread and not related to the SDK itself nor do I think your code is causing these rate limits. We are seeing reports from falconpy & powershell users too including internal teams.

As far as rate limits here are the docs:

> All requests to the CrowdStrike API are subject to a rate limit.
> 
> The default rate limit for requests containing a valid bearer token is 6,000 requests per minute per customer account. Each request in your customer account removes one request from that pool, regardless of which API endpoint or API client is used for the request. The rate limit is calculated on a sliding window.
> 
> Requests with missing, malformed, or expired bearer tokens are rate limited at 15 requests per minute per source IP address (not per customer account).

This is what I was referring to on IP based rate limits: `Requests with missing, malformed, or expired bearer tokens are rate limited at 15 requests per minute per source IP address (not per customer account).` For `/oauth2/token` the 15 requests per minute is overridden to allow 300 per IP per minute. Overrides are not documented to allow them to change as needed, but you can use the `X-Ratelimit-Limit` header to see this. None of this applies to the current situation, but in the future maybe it will be handy :)

Thanks again for pointing out that bug in autodiscover!

**Comment by jshcodes** [comment]
> The 429 errors you were seeing seems to be widespread and not related to the SDK itself nor do I think your code is causing these rate limits. We are seeing reports from falconpy & powershell users too including internal teams.

The 429 issue should also be resolved now. Let us know if you're still seeing it.

**Comment by bionic-ido** [comment]
Hey, that's awesome turnover from when I opened the issue to when there is already a new version to use, thanks! :)
