### ISSUE TITLE
RTR Update Scripts is throwing a has a status 202 in the error code when updating a script

### ISSUE THREAD

**Issue by terrancedjones** [CrowdStrike/gofalcon#408]
When we update a script with RTRUpdateScripts we get an error response with status 202 not sure why an error is being thrown with status 202.  The script is updated successfully and we see the changes, but we still receive an error with status 202 in the error return value. 

Thanks and have a great day.

**Comment by ffalor** [comment]
hey `0.7.0-rc1` adds 202 as a possible response.
