### ISSUE TITLE
Inconsistent model mapping (domain_user)

### ISSUE THREAD

**Issue by martinalbert** [CrowdStrike/gofalcon#425]
This issue describes inconsistent mapping of model `DomainUser`. This change happened in 97a91119047afa8f3c6f71f4b0506a63d2a2ba1d.

### Current structure of `DomainUser` from endpoint `https://api.crowdstrike.com/user-management/entities/users/GET/v1`:
<img width="550" alt="image" src="https://github.com/CrowdStrike/gofalcon/assets/17796870/f6552ca0-1be6-454a-a017-0e259ea9bef6">

### Type in code:
https://github.com/CrowdStrike/gofalcon/blob/48f6999d0fa4c4e056d3d42553fad6a7abb599d7/falcon/models/domain_user.go#L18-L34

Other types of `DomainUser` like `DomainCreateUserRequest` contain the old structure: https://github.com/CrowdStrike/gofalcon/blob/48f6999d0fa4c4e056d3d42553fad6a7abb599d7/falcon/models/domain_create_user_request.go#L18-L34

**Comment by martinalbert** [comment]
Thank you @ffalor, seems like the release action went through, but I can't use the new release candidate. I can't find it in go registry as well: https://pkg.go.dev/github.com/crowdstrike/gofalcon?tab=versions.

**Comment by ffalor** [comment]
It's because it's marked as a pre-release. You can install it by running `go get github.com/crowdstrike/gofalcon/falcon@0.7.0-rc1`

It will look like this in your `go.mod` file: `github.com/crowdstrike/gofalcon v0.6.1-0.20240426204036-ac8ce2b4f2d7`

**Comment by martinalbert** [comment]
My bad, thank you again @ffalor, it works!
