### ISSUE TITLE
Fetch Cloud Misconfigurations via SDK

### ISSUE THREAD

**Issue by hazcod** [CrowdStrike/gofalcon#433]
Hi there!

Is there a way to fetch Cloud Security misconfigurations via this SDK?
I couldn't immediately find a method to do so. Thanks!

**Comment by ffalor** [comment]
@hazcod are you referring to IOM's, in cloud security posture management? Does this get you want you need? `client.CspmRegistration.GetConfigurationDetectionIDsV2()`

The kubernetes protection service collection has IOMs also 
<img width="668" alt="image" src="https://github.com/CrowdStrike/gofalcon/assets/35144141/2851d37e-d947-4ede-ba73-6e296e71fced">

**Comment by hazcod** [comment]
That's it, thank you!

**Comment by hazcod** [comment]
I was wondering @ffalor , this call just keeps loading:
![image](https://github.com/CrowdStrike/gofalcon/assets/5222512/696614fe-3779-4383-a3f9-cdefb2899b8f)

So Im presuming i'm doing something wrong here, since it never completes.

**Comment by ffalor** [comment]
I can tell the filter is currently wrong, but even using a bad filter mine completed with an `400` status code.

Below is a working example

```Golang
package main

import (
	"context"
	"fmt"
	"os"

	"github.com/crowdstrike/gofalcon/falcon"
	"github.com/crowdstrike/gofalcon/falcon/client/cspm_registration"
	"github.com/crowdstrike/gofalcon/pkg/falcon_util"
)

func main() {
	falconClientId := os.Getenv("FALCON_CLIENT_ID")
	falconClientSecret := os.Getenv("FALCON_CLIENT_SECRET")
	clientCloud := os.Getenv("FALCON_CLOUD")

	client, err := falcon.NewClient(&falcon.ApiConfig{
		ClientId:     falconClientId,
		ClientSecret: falconClientSecret,
		Cloud:        falcon.Cloud(clientCloud),
		Context:      context.Background(),
	})
	if err != nil {
		panic(err)
	}

	filter := "use_current_scan_ids:true"
	limit := int64(10)

	res, err := client.CspmRegistration.GetConfigurationDetectionIDsV2(
		&cspm_registration.GetConfigurationDetectionIDsV2Params{
			Context: context.Background(),
			Filter:  &filter,
			Limit:   &limit,
		},
	)

	fmt.Printf("Response: %v\n", res)
	fmt.Printf("Error: %v\n", err)
}
```
