### ISSUE TITLE
Alerts details truncated

### ISSUE THREAD

**Issue by taki-mekhalfa** [CrowdStrike/gofalcon#452]
Hi,

When getting alerts via `GetV2` (`/alerts/entities/alerts/v2`). The returned alerts detailed are truncated from the response

For example in case of a binary execution:

- filename
- username
- device

Would it be possible to please update?

Thank you

**Comment by ffalor** [comment]
Hey @taki-mekhalfa, thanks for reporting, this is probably due to the return type not having the correct fields in the struct. I'll take a look at this when I am regenerating the SDK.

I'll try to have a new version out by end of next week.

**Comment by ffalor** [comment]
@taki-mekhalfa I'm reached out to the API owners in hopes of getting this resolved.

**Comment by ffalor** [comment]
Hey @taki-mekhalfa sorry for the delay. I've released `v0.9.0` 

The fields returned from the `alerts` endpoint are very dynamic and change depending on the type of alert that is thrown. I've done extensive testing and mapped all the fields I'm aware off. If you come across a field that is missing please let me know, and I'll make the necessary changes.

Thank you again for your patience and letting me know about this gap.

**Comment by taki-mekhalfa** [comment]
Hello ffalor, thanks for the time spent on this issue. 

Do you have a solution for getting these dynamic field when needed through this go client ?
