### ISSUE TITLE
Wrong Endpoint Detections information after console view deprecation

### ISSUE THREAD

**Issue by l-teles** [CrowdStrike/gofalcon#453]
Hi 👋

After the [decommissioning of the Endpoint Detections (Deprecated) Console Experience](https://supportportal.crowdstrike.com/s/article/Tech-Alert-Decommissioning-of-the-Endpoint-Detections-Deprecated-Console-Experience), the information retrievable from the `getDetectsDetails` function no longer makes sense, as it doesn't reflect the information about the detections currently visible on the console. 

Since there is no sync between the Updated and Deprecated detections API, the detections info is outdated and not relevant since the 1st of September, when the deprecated experience was effectively deprecated. 

Can you please update the `GetAggregateDetects` function to fetch from the new source of data (which I'm not sure which it actually is?) instead of the old `/detects/aggregates/detects/GET/v1` endpoint?

Thank you!

**Comment by ffalor** [comment]
Hey @l-teles I'll take a look at this when I am regenerating the sdk.

I plan on having a new version by end of next week.

Thank's for reporting the issue!

**Comment by ffalor** [comment]
Hey @l-teles 

Looks like you've identified two issue.

1. `getDetectsDetails` what information is missing that should be available?
2. `GetAggregateDetects` I am working with endpoint owner to get the correct api spec to be used to generate this endpoint.

**Comment by ffalor** [comment]
Hey @l-teles i've talked with the folks in charge of these apis. There is a[ conversion guide](https://falcon.crowdstrike.com/documentation/page/d02475a5/converting-from-detects-api-to-alerts-api#w2107f72).

According to this guide:

`GetDetectSummaries` is replaced by `alerts.QueryV2`
`GetAggregateDetects` is replaced by `alerts.GetAggregateV2`

Closing for now, but if these don't work feel free to reopen!

**Comment by ffalor** [comment]
hey @l-teles @rajlearner17 I'm not sure I understand the ask here? Happy to help once I understand.

**Comment by ffalor** [comment]
@l-teles sorry for the late reply, does this help?

[detects-to-alerts-migration.md](https://github.com/user-attachments/files/21799825/detects-to-alerts-migration.md)

**Comment by misraved** [comment]
Thanks a lot @ffalor and @l-teles for all the help 👍 !!
