### ISSUE TITLE
No method for performPreventionPoliciesAction

### ISSUE THREAD

**Issue by gnuletik** [CrowdStrike/gofalcon#458]
The `gofalcon` package doesn't expose a method to interact with the `performPreventionPoliciesAction` operation of the falcon API (`POST ​/policy​/entities​/prevention-actions​/v1`).

**Comment by ffalor** [comment]
Hey @gnuletik we do have this method in the sdk. [Here is an example](https://github.com/CrowdStrike/terraform-provider-crowdstrike/blob/24c720a82a0b7ce9961d597d1e71dd9dc9bae506/internal/prevention_policy/shared.go#L75-L145) of using it to update rule groups on a prevention policy. 

```Go
res, err := client.PreventionPolicies.PerformPreventionPoliciesAction(
		&prevention_policies.PerformPreventionPoliciesActionParams{
			Context:    ctx,
			ActionName: action.String(),
			Body: &models.MsaEntityActionRequestV2{
				ActionParameters: actionParams,
				Ids:              []string{id},
			},
		},
	)
```

**Comment by gnuletik** [comment]
Thanks for this!
I looked for the method through Github search but Github doesn't seem to search through all files.

**Comment by ffalor** [comment]
No problem, I noticed that too when trying to find it. I had to use neovim.
