### ISSUE TITLE
[Feature] Add Support for member CID MSSP targeting

### ISSUE THREAD

**Issue by StefanDorresteijn** [CrowdStrike/gofalcon#59]
**Is your feature request related to a problem? Please describe.**
For customers with MSSP (Master/member) we need to support using master API credentials to lock the token to member CIDs.

**Describe the solution you'd like**
Either adding a value to the `falcon.ApiConfig` struct that allows for a MemberCID (the way `Oauth2AccessTokenParams` already has it) so that you can set the MemberCID right from the beginning, or adding the ability to set this value later on/per request.

**Describe alternatives you've considered**
Currently our solution is simply creating API keys for every single CID, which is difficult to do in a safe way. 

**Additional notes**
The `Oauth2.Oauth2AccessToken` function already allows for the creation of this token, but I don't see a way to use the token in a falcon client. If there is a way to do it, some documentation on that would be useful.

**Comment by isimluk** [comment]
Thanks for reporting @StefanDorresteijn.

This is certainly on my todo list, will prioritise it bit for you.

**Comment by isimluk** [comment]
@StefanDorresteijn, I think I just got this working in #60. Please reach out it does not work as expected.

**Comment by isimluk** [comment]
(will release new version after it gets merged)

**Comment by shawndwells** [comment]
> (will release new version after it gets merged)

Merged

**Comment by StefanDorresteijn** [comment]
This works perfectly, thanks!
