### ISSUE TITLE
Feature: fetch mitigations

### ISSUE THREAD

**Issue by hazcod** [CrowdStrike/gofalcon#80]
Would be nice to be able to fetch the mitigations for Spotlight vulnerabilities.

**Comment by isimluk** [comment]
Thank You @hazcod for bringing this issue to my attention.

I have found that there is indeed a way of querying the mitigations through the API.

https://falcon.crowdstrike.com/documentation/98/spotlight-apis#finding-remedations 

For some reason, however, this API is not available through swagger doc and thus not part of gofalcon yet. Let me leave this issues open before I know more.

**Comment by isimluk** [comment]
@hazcod, the Spotlight remediations are now available through gofalcon. Please see #104 for the information how to use it.

**Comment by hazcod** [comment]
Super! Will you create a new release @isimluk ?

**Comment by isimluk** [comment]
Done, @hazcod. https://github.com/CrowdStrike/gofalcon/releases/tag/v0.2.8
