### ISSUE TITLE
Event Streams with Mixed Types (string and uint64) for Event.event.ProcessId

### ISSUE THREAD

**Issue by ryan-theta** [CrowdStrike/gofalcon#83]
Hey,

I'm failing to receive certain events on the stream because the detections are coming through a process ID and parent process ID of strings instead of ints

> ERROR: json: cannot unmarshal string into Go struct field Event.event.ProcessId of type uint64

[Type setting](https://github.com/CrowdStrike/gofalcon/blob/5703b0cd1a0a53e1865e80387a3235fb137b5e46/falcon/models/streaming_models/models.go#L40)

By the time this occurs the events are already exposed in the error channel

```
		for fatal == nil {
			select {
			case err := <-stream.Errors:
				if err.Fatal {
					fatal = err.Err
				} else {
                                          // error received here
					fmt.Fprintln(os.Stderr, err)
				}
			case event := <-stream.Events:
				if int(event.Metadata.Offset) >= intStart && int(event.Metadata.Offset) <= intEnd {
					handleEvent(event)
				}
			}
		}

```

Whenever we receive a detection event we follow up and request more host and detection details anyway - as far as i'm concerned removing the ProcessID and ParentProcessID from the struct is good enough. Although, it's possible the same problem will occur in the detects models...

**Comment by isimluk** [comment]
Thank You @ryan-theta, for bringing this issue to my attention.

It seems that the processID may be int or string based on the underlying operating system. 

I think I have fixed this in #86, but I would appreciate your testing as I haven't been able to reproduce the String behavior you are seeing. I am seeing only Ints in my event stream.

To your concern about the other APIs being affected; I think that is fairly unlikely given different mechanisms being used on both ends (client vs server and stream vs api).

**Comment by ryan-theta** [comment]
@isimluk 
Thanks, understand it's tricky to test.  Both of my test events fail with a new error, looks like they've got a blank string, not a numbered string for processId:
Event received but couldn't be parsed

strconv.ParseUint: parsing "": invalid syntax
ERROR: strconv.ParseUint: parsing "": invalid syntax

Needs a blank check at https://github.com/isimluk/gofalcon/blob/c60c8a25e5f37700f23f869cf5fbed56c4b09087/falcon/models/streaming_models/utils.go#L23

**Comment by isimluk** [comment]
Oh, Thank You @ryan-theta for reporting this. Hopefully, it works now with the patch in #88.
